<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run()
    {
        DB::table('countries')->insert([
                ["id" => 1,"dial_code"=>93,"name"=>"Afghanistan","code"=>"AF"],
                ["id" => 2,"dial_code"=>358,"name"=>"Aland Islands","code"=>"AX"],
                ["id" => 3,"dial_code"=>355,"name"=>"Albania","code"=>"AL"],
                ["id" => 4,"dial_code"=>213,"name"=>"Algeria","code"=>"DZ"],
                ["id" => 5,"dial_code"=>1684,"name"=>"AmericanSamoa","code"=>"AS"],
                ["id" => 6,"dial_code"=>376,"name"=>"Andorra","code"=>"AD"],
                ["id" => 7,"dial_code"=>244,"name"=>"Angola","code"=>"AO"],
                ["id" => 8,"dial_code"=>1264,"name"=>"Anguilla","code"=>"AI"],
                ["id" => 9,"dial_code"=>672,"name"=>"Antarctica","code"=>"AQ"],
                ["id" => 10,"dial_code"=>1268,"name"=>"Antigua and Barbuda","code"=>"AG"],
                ["id" => 11,"dial_code"=>54,"name"=>"Argentina","code"=>"AR"],
                ["id" => 12,"dial_code"=>374,"name"=>"Armenia","code"=>"AM"],
                ["id" => 13,"dial_code"=>297,"name"=>"Aruba","code"=>"AW"],
                ["id" => 14,"dial_code"=>61,"name"=>"Australia","code"=>"AU"],
                ["id" => 15,"dial_code"=>43,"name"=>"Austria","code"=>"AT"],
                ["id" => 16,"dial_code"=>994,"name"=>"Azerbaijan","code"=>"AZ"],
                ["id" => 17,"dial_code"=>1242,"name"=>"Bahamas","code"=>"BS"],
                ["id" => 18,"dial_code"=>973,"name"=>"Bahrain","code"=>"BH"],
                ["id" => 19,"dial_code"=>880,"name"=>"Bangladesh","code"=>"BD"],
                ["id" => 20,"dial_code"=>1246,"name"=>"Barbados","code"=>"BB"],
                ["id" => 21,"dial_code"=>375,"name"=>"Belarus","code"=>"BY"],
                ["id" => 22,"dial_code"=>32,"name"=>"Belgium","code"=>"BE"],
                ["id" => 23,"dial_code"=>501,"name"=>"Belize","code"=>"BZ"],
                ["id" => 24,"dial_code"=>229,"name"=>"Benin","code"=>"BJ"],
                ["id" => 25,"dial_code"=>1441,"name"=>"Bermuda","code"=>"BM"],
                ["id" => 26,"dial_code"=>975,"name"=>"Bhutan","code"=>"BT"],
                ["id" => 27,"dial_code"=>591,"name"=>"Bolivia, Plurinational State of","code"=>"BO"],
                ["id" => 28,"dial_code"=>387,"name"=>"Bosnia and Herzegovina","code"=>"BA"],
                ["id" => 29,"dial_code"=>267,"name"=>"Botswana","code"=>"BW"],
                ["id" => 30,"dial_code"=>55,"name"=>"Brazil","code"=>"BR"],
                ["id" => 31,"dial_code"=>246,"name"=>"British Indian Ocean Territory","code"=>"IO"],
                ["id" => 32,"dial_code"=>673,"name"=>"Brunei Darussalam","code"=>"BN"],
                ["id" => 33,"dial_code"=>359,"name"=>"Bulgaria","code"=>"BG"],
                ["id" => 34,"dial_code"=>226,"name"=>"Burkina Faso","code"=>"BF"],
                ["id" => 35,"dial_code"=>257,"name"=>"Burundi","code"=>"BI"],
                ["id" => 36,"dial_code"=>855,"name"=>"Cambodia","code"=>"KH"],
                ["id" => 37,"dial_code"=>237,"name"=>"Cameroon","code"=>"CM"],
                ["id" => 38,"dial_code"=>1,"name"=>"Canada","code"=>"CA"],
                ["id" => 39,"dial_code"=>238,"name"=>"Cape Verde","code"=>"CV"],
                ["id" => 40,"dial_code"=>345,"name"=>"Cayman Islands","code"=>"KY"],
                ["id" => 41,"dial_code"=>236,"name"=>"Central African Republic","code"=>"CF"],
                ["id" => 42,"dial_code"=>235,"name"=>"Chad","code"=>"TD"],
                ["id" => 43,"dial_code"=>56,"name"=>"Chile","code"=>"CL"],
                ["id" => 44,"dial_code"=>86,"name"=>"China","code"=>"CN"],
                ["id" => 45,"dial_code"=>61,"name"=>"Christmas Island","code"=>"CX"],
                ["id" => 46,"dial_code"=>61,"name"=>"Cocos (Keeling) Islands","code"=>"CC"],
                ["id" => 47,"dial_code"=>57,"name"=>"Colombia","code"=>"CO"],
                ["id" => 48,"dial_code"=>269,"name"=>"Comoros","code"=>"KM"],
                ["id" => 49,"dial_code"=>242,"name"=>"Congo","code"=>"CG"],
                ["id" => 50,"dial_code"=>243,"name"=>"Congo, The Democratic Republic of the Congo","code"=>"CD"],
                ["id" => 51,"dial_code"=>682,"name"=>"Cook Islands","code"=>"CK"],
                ["id" => 52,"dial_code"=>506,"name"=>"Costa Rica","code"=>"CR"],
                ["id" => 53,"dial_code"=>225,"name"=>"Cote d'Ivoire","code"=>"CI"],
                ["id" => 54,"dial_code"=>385,"name"=>"Croatia","code"=>"HR"],
                ["id" => 55,"dial_code"=>53,"name"=>"Cuba","code"=>"CU"],
                ["id" => 56,"dial_code"=>357,"name"=>"Cyprus","code"=>"CY"],
                ["id" => 57,"dial_code"=>420,"name"=>"Czech Republic","code"=>"CZ"],
                ["id" => 58,"dial_code"=>45,"name"=>"Denmark","code"=>"DK"],
                ["id" => 59,"dial_code"=>253,"name"=>"Djibouti","code"=>"DJ"],
                ["id" => 60,"dial_code"=>1767,"name"=>"Dominica","code"=>"DM"],
                ["id" => 61,"dial_code"=>1849,"name"=>"Dominican Republic","code"=>"DO"],
                ["id" => 62,"dial_code"=>593,"name"=>"Ecuador","code"=>"EC"],
                ["id" => 63,"dial_code"=>20,"name"=>"Egypt","code"=>"EG"],
                ["id" => 64,"dial_code"=>503,"name"=>"El Salvador","code"=>"SV"],
                ["id" => 65,"dial_code"=>240,"name"=>"Equatorial Guinea","code"=>"GQ"],
                ["id" => 66,"dial_code"=>291,"name"=>"Eritrea","code"=>"ER"],
                ["id" => 67,"dial_code"=>372,"name"=>"Estonia","code"=>"EE"],
                ["id" => 68,"dial_code"=>251,"name"=>"Ethiopia","code"=>"ET"],
                ["id" => 69,"dial_code"=>500,"name"=>"Falkland Islands (Malvinas)","code"=>"FK"],
                ["id" => 70,"dial_code"=>298,"name"=>"Faroe Islands","code"=>"FO"],
                ["id" => 71,"dial_code"=>679,"name"=>"Fiji","code"=>"FJ"],
                ["id" => 72,"dial_code"=>358,"name"=>"Finland","code"=>"FI"],
                ["id" => 73,"dial_code"=>33,"name"=>"France","code"=>"FR"],
                ["id" => 74,"dial_code"=>594,"name"=>"French Guiana","code"=>"GF"],
                ["id" => 75,"dial_code"=>689,"name"=>"French Polynesia","code"=>"PF"],
                ["id" => 76,"dial_code"=>241,"name"=>"Gabon","code"=>"GA"],
                ["id" => 77,"dial_code"=>220,"name"=>"Gambia","code"=>"GM"],
                ["id" => 78,"dial_code"=>995,"name"=>"Georgia","code"=>"GE"],
                ["id" => 79,"dial_code"=>49,"name"=>"Germany","code"=>"DE"],
                ["id" => 80,"dial_code"=>233,"name"=>"Ghana","code"=>"GH"],
                ["id" => 81,"dial_code"=>350,"name"=>"Gibraltar","code"=>"GI"],
                ["id" => 82,"dial_code"=>30,"name"=>"Greece","code"=>"GR"],
                ["id" => 83,"dial_code"=>299,"name"=>"Greenland","code"=>"GL"],
                ["id" => 84,"dial_code"=>1473,"name"=>"Grenada","code"=>"GD"],
                ["id" => 85,"dial_code"=>590,"name"=>"Guadeloupe","code"=>"GP"],
                ["id" => 86,"dial_code"=>1671,"name"=>"Guam","code"=>"GU"],
                ["id" => 87,"dial_code"=>502,"name"=>"Guatemala","code"=>"GT"],
                ["id" => 88,"dial_code"=>44,"name"=>"Guernsey","code"=>"GG"],
                ["id" => 89,"dial_code"=>224,"name"=>"Guinea","code"=>"GN"],
                ["id" => 90,"dial_code"=>245,"name"=>"Guinea-Bissau","code"=>"GW"],
                ["id" => 91,"dial_code"=>595,"name"=>"Guyana","code"=>"GY"],
                ["id" => 92,"dial_code"=>509,"name"=>"Haiti","code"=>"HT"],
                ["id" => 93,"dial_code"=>379,"name"=>"Holy See (Vatican City State)","code"=>"VA"],
                ["id" => 94,"dial_code"=>504,"name"=>"Honduras","code"=>"HN"],
                ["id" => 95,"dial_code"=>852,"name"=>"Hong Kong","code"=>"HK"],
                ["id" => 96,"dial_code"=>36,"name"=>"Hungary","code"=>"HU"],
                ["id" => 97,"dial_code"=>354,"name"=>"Iceland","code"=>"IS"],
                ["id" => 98,"dial_code"=>91,"name"=>"India","code"=>"IN"],
                ["id" => 99,"dial_code"=>62,"name"=>"Indonesia","code"=>"ID"],
                ["id" => 100,"dial_code"=>98,"name"=>"Iran, Islamic Republic of Persian Gulf","code"=>"IR"],
                ["id" => 101,"dial_code"=>964,"name"=>"Iraq","code"=>"IQ"],
                ["id" => 102,"dial_code"=>353,"name"=>"Ireland","code"=>"IE"],
                ["id" => 103,"dial_code"=>44,"name"=>"Isle of Man","code"=>"IM"],
                ["id" => 104,"dial_code"=>972,"name"=>"Israel","code"=>"IL"],
                ["id" => 105,"dial_code"=>39,"name"=>"Italy","code"=>"IT"],
                ["id" => 106,"dial_code"=>1876,"name"=>"Jamaica","code"=>"JM"],
                ["id" => 107,"dial_code"=>81,"name"=>"Japan","code"=>"JP"],
                ["id" => 108,"dial_code"=>44,"name"=>"Jersey","code"=>"JE"],
                ["id" => 109,"dial_code"=>962,"name"=>"Jordan","code"=>"JO"],
                ["id" => 110,"dial_code"=>77,"name"=>"Kazakhstan","code"=>"KZ"],
                ["id" => 111,"dial_code"=>254,"name"=>"Kenya","code"=>"KE"],
                ["id" => 112,"dial_code"=>686,"name"=>"Kiribati","code"=>"KI"],
                ["id" => 113,"dial_code"=>850,"name"=>"Korea, Democratic People's Republic of Korea","code"=>"KP"],
                ["id" => 114,"dial_code"=>82,"name"=>"Korea, Republic of South Korea","code"=>"KR"],
                ["id" => 115,"dial_code"=>965,"name"=>"Kuwait","code"=>"KW"],
                ["id" => 116,"dial_code"=>996,"name"=>"Kyrgyzstan","code"=>"KG"],
                ["id" => 117,"dial_code"=>856,"name"=>"Laos","code"=>"LA"],
                ["id" => 118,"dial_code"=>371,"name"=>"Latvia","code"=>"LV"],
                ["id" => 119,"dial_code"=>961,"name"=>"Lebanon","code"=>"LB"],
                ["id" => 120,"dial_code"=>266,"name"=>"Lesotho","code"=>"LS"],
                ["id" => 121,"dial_code"=>231,"name"=>"Liberia","code"=>"LR"],
                ["id" => 122,"dial_code"=>218,"name"=>"Libyan Arab Jamahiriya","code"=>"LY"],
                ["id" => 123,"dial_code"=>423,"name"=>"Liechtenstein","code"=>"LI"],
                ["id" => 124,"dial_code"=>370,"name"=>"Lithuania","code"=>"LT"],
                ["id" => 125,"dial_code"=>352,"name"=>"Luxembourg","code"=>"LU"],
                ["id" => 126,"dial_code"=>853,"name"=>"Macao","code"=>"MO"],
                ["id" => 127,"dial_code"=>389,"name"=>"Macedonia","code"=>"MK"],
                ["id" => 128,"dial_code"=>261,"name"=>"Madagascar","code"=>"MG"],
                ["id" => 129,"dial_code"=>265,"name"=>"Malawi","code"=>"MW"],
                ["id" => 130,"dial_code"=>60,"name"=>"Malaysia","code"=>"MY"],
                ["id" => 131,"dial_code"=>960,"name"=>"Maldives","code"=>"MV"],
                ["id" => 132,"dial_code"=>223,"name"=>"Mali","code"=>"ML"],
                ["id" => 133,"dial_code"=>356,"name"=>"Malta","code"=>"MT"],
                ["id" => 134,"dial_code"=>692,"name"=>"Marshall Islands","code"=>"MH"],
                ["id" => 135,"dial_code"=>596,"name"=>"Martinique","code"=>"MQ"],
                ["id" => 136,"dial_code"=>222,"name"=>"Mauritania","code"=>"MR"],
                ["id" => 137,"dial_code"=>230,"name"=>"Mauritius","code"=>"MU"],
                ["id" => 138,"dial_code"=>262,"name"=>"Mayotte","code"=>"YT"],
                ["id" => 139,"dial_code"=>52,"name"=>"Mexico","code"=>"MX"],
                ["id" => 140,"dial_code"=>691,"name"=>"Micronesia, Federated States of Micronesia","code"=>"FM"],
                ["id" => 141,"dial_code"=>373,"name"=>"Moldova","code"=>"MD"],
                ["id" => 142,"dial_code"=>377,"name"=>"Monaco","code"=>"MC"],
                ["id" => 143,"dial_code"=>976,"name"=>"Mongolia","code"=>"MN"],
                ["id" => 144,"dial_code"=>382,"name"=>"Montenegro","code"=>"ME"],
                ["id" => 145,"dial_code"=>1664,"name"=>"Montserrat","code"=>"MS"],
                ["id" => 146,"dial_code"=>212,"name"=>"Morocco","code"=>"MA"],
                ["id" => 147,"dial_code"=>258,"name"=>"Mozambique","code"=>"MZ"],
                ["id" => 148,"dial_code"=>95,"name"=>"Myanmar","code"=>"MM"],
                ["id" => 149,"dial_code"=>264,"name"=>"Namibia","code"=>"NA"],
                ["id" => 150,"dial_code"=>674,"name"=>"Nauru","code"=>"NR"],
                ["id" => 151,"dial_code"=>977,"name"=>"Nepal","code"=>"NP"],
                ["id" => 152,"dial_code"=>31,"name"=>"Netherlands","code"=>"NL"],
                ["id" => 153,"dial_code"=>599,"name"=>"Netherlands Antilles","code"=>"AN"],
                ["id" => 154,"dial_code"=>687,"name"=>"New Caledonia","code"=>"NC"],
                ["id" => 155,"dial_code"=>64,"name"=>"New Zealand","code"=>"NZ"],
                ["id" => 156,"dial_code"=>505,"name"=>"Nicaragua","code"=>"NI"],
                ["id" => 157,"dial_code"=>227,"name"=>"Niger","code"=>"NE"],
                ["id" => 158,"dial_code"=>234,"name"=>"Nigeria","code"=>"NG"],
                ["id" => 159,"dial_code"=>683,"name"=>"Niue","code"=>"NU"],
                ["id" => 160,"dial_code"=>672,"name"=>"Norfolk Island","code"=>"NF"],
                ["id" => 161,"dial_code"=>1670,"name"=>"Northern Mariana Islands","code"=>"MP"],
                ["id" => 162,"dial_code"=>47,"name"=>"Norway","code"=>"NO"],
                ["id" => 163,"dial_code"=>968,"name"=>"Oman","code"=>"OM"],
                ["id" => 164,"dial_code"=>92,"name"=>"Pakistan","code"=>"PK"],
                ["id" => 165,"dial_code"=>680,"name"=>"Palau","code"=>"PW"],
                ["id" => 166,"dial_code"=>970,"name"=>"Palestinian Territory, Occupied","code"=>"PS"],
                ["id" => 167,"dial_code"=>507,"name"=>"Panama","code"=>"PA"],
                ["id" => 168,"dial_code"=>675,"name"=>"Papua New Guinea","code"=>"PG"],
                ["id" => 169,"dial_code"=>595,"name"=>"Paraguay","code"=>"PY"],
                ["id" => 170,"dial_code"=>51,"name"=>"Peru","code"=>"PE"],
                ["id" => 171,"dial_code"=>63,"name"=>"Philippines","code"=>"PH"],
                ["id" => 172,"dial_code"=>872,"name"=>"Pitcairn","code"=>"PN"],
                ["id" => 173,"dial_code"=>48,"name"=>"Poland","code"=>"PL"],
                ["id" => 174,"dial_code"=>351,"name"=>"Portugal","code"=>"PT"],
                ["id" => 175,"dial_code"=>1939,"name"=>"Puerto Rico","code"=>"PR"],
                ["id" => 176,"dial_code"=>974,"name"=>"Qatar","code"=>"QA"],
                ["id" => 177,"dial_code"=>40,"name"=>"Romania","code"=>"RO"],
                ["id" => 178,"dial_code"=>7,"name"=>"Russia","code"=>"RU"],
                ["id" => 179,"dial_code"=>250,"name"=>"Rwanda","code"=>"RW"],
                ["id" => 180,"dial_code"=>262,"name"=>"Reunion","code"=>"RE"],
                ["id" => 181,"dial_code"=>590,"name"=>"Saint Barthelemy","code"=>"BL"],
                ["id" => 182,"dial_code"=>290,"name"=>"Saint Helena, Ascension and Tristan Da Cunha","code"=>"SH"],
                ["id" => 183,"dial_code"=>1869,"name"=>"Saint Kitts and Nevis","code"=>"KN"],
                ["id" => 184,"dial_code"=>1758,"name"=>"Saint Lucia","code"=>"LC"],
                ["id" => 185,"dial_code"=>590,"name"=>"Saint Martin","code"=>"MF"],
                ["id" => 186,"dial_code"=>508,"name"=>"Saint Pierre and Miquelon","code"=>"PM"],
                ["id" => 187,"dial_code"=>1784,"name"=>"Saint Vincent and the Grenadines","code"=>"VC"],
                ["id" => 188,"dial_code"=>685,"name"=>"Samoa","code"=>"WS"],
                ["id" => 189,"dial_code"=>378,"name"=>"San Marino","code"=>"SM"],
                ["id" => 190,"dial_code"=>239,"name"=>"Sao Tome and Principe","code"=>"ST"],
                ["id" => 191,"dial_code"=>966,"name"=>"Saudi Arabia","code"=>"SA"],
                ["id" => 192,"dial_code"=>221,"name"=>"Senegal","code"=>"SN"],
                ["id" => 193,"dial_code"=>381,"name"=>"Serbia","code"=>"RS"],
                ["id" => 194,"dial_code"=>248,"name"=>"Seychelles","code"=>"SC"],
                ["id" => 195,"dial_code"=>232,"name"=>"Sierra Leone","code"=>"SL"],
                ["id" => 196,"dial_code"=>65,"name"=>"Singapore","code"=>"SG"],
                ["id" => 197,"dial_code"=>421,"name"=>"Slovakia","code"=>"SK"],
                ["id" => 198,"dial_code"=>386,"name"=>"Slovenia","code"=>"SI"],
                ["id" => 199,"dial_code"=>677,"name"=>"Solomon Islands","code"=>"SB"],
                ["id" => 200,"dial_code"=>252,"name"=>"Somalia","code"=>"SO"],
                ["id" => 201,"dial_code"=>27,"name"=>"South Africa","code"=>"ZA"],
                ["id" => 202,"dial_code"=>211,"name"=>"South Sudan","code"=>"SS"],
                ["id" => 203,"dial_code"=>500,"name"=>"South Georgia and the South Sandwich Islands","code"=>"GS"],
                ["id" => 204,"dial_code"=>34,"name"=>"Spain","code"=>"ES"],
                ["id" => 205,"dial_code"=>94,"name"=>"Sri Lanka","code"=>"LK"],
                ["id" => 206,"dial_code"=>249,"name"=>"Sudan","code"=>"SD"],
                ["id" => 207,"dial_code"=>597,"name"=>"Suriname","code"=>"SR"],
                ["id" => 208,"dial_code"=>47,"name"=>"Svalbard and Jan Mayen","code"=>"SJ"],
                ["id" => 209,"dial_code"=>268,"name"=>"Swaziland","code"=>"SZ"],
                ["id" => 210,"dial_code"=>46,"name"=>"Sweden","code"=>"SE"],
                ["id" => 211,"dial_code"=>41,"name"=>"Switzerland","code"=>"CH"],
                ["id" => 212,"dial_code"=>963,"name"=>"Syrian Arab Republic","code"=>"SY"],
                ["id" => 213,"dial_code"=>886,"name"=>"Taiwan","code"=>"TW"],
                ["id" => 214,"dial_code"=>992,"name"=>"Tajikistan","code"=>"TJ"],
                ["id" => 215,"dial_code"=>255,"name"=>"Tanzania, United Republic of Tanzania","code"=>"TZ"],
                ["id" => 216,"dial_code"=>66,"name"=>"Thailand","code"=>"TH"],
                ["id" => 217,"dial_code"=>670,"name"=>"Timor-Leste","code"=>"TL"],
                ["id" => 218,"dial_code"=>228,"name"=>"Togo","code"=>"TG"],
                ["id" => 219,"dial_code"=>690,"name"=>"Tokelau","code"=>"TK"],
                ["id" => 220,"dial_code"=>676,"name"=>"Tonga","code"=>"TO"],
                ["id" => 221,"dial_code"=>1868,"name"=>"Trinidad and Tobago","code"=>"TT"],
                ["id" => 222,"dial_code"=>216,"name"=>"Tunisia","code"=>"TN"],
                ["id" => 223,"dial_code"=>90,"name"=>"Turkey","code"=>"TR"],
                ["id" => 224,"dial_code"=>993,"name"=>"Turkmenistan","code"=>"TM"],
                ["id" => 225,"dial_code"=>1649,"name"=>"Turks and Caicos Islands","code"=>"TC"],
                ["id" => 226,"dial_code"=>688,"name"=>"Tuvalu","code"=>"TV"],
                ["id" => 227,"dial_code"=>256,"name"=>"Uganda","code"=>"UG"],
                ["id" => 228,"dial_code"=>380,"name"=>"Ukraine","code"=>"UA"],
                ["id" => 229,"dial_code"=>971,"name"=>"United Arab Emirates","code"=>"AE"],
                ["id" => 230,"dial_code"=>44,"name"=>"United Kingdom","code"=>"GB"],
                ["id" => 231,"dial_code"=>1,"name"=>"United States","code"=>"US"],
                ["id" => 232,"dial_code"=>598,"name"=>"Uruguay","code"=>"UY"],
                ["id" => 233,"dial_code"=>998,"name"=>"Uzbekistan","code"=>"UZ"],
                ["id" => 234,"dial_code"=>678,"name"=>"Vanuatu","code"=>"VU"],
                ["id" => 235,"dial_code"=>58,"name"=>"Venezuela, Bolivarian Republic of Venezuela","code"=>"VE"],
                ["id" => 236,"dial_code"=>84,"name"=>"Vietnam","code"=>"VN"],
                ["id" => 237,"dial_code"=>1284,"name"=>"Virgin Islands, British","code"=>"VG"],
                ["id" => 238,"dial_code"=>1340,"name"=>"Virgin Islands, U.S.","code"=>"VI"],
                ["id" => 239,"dial_code"=>681,"name"=>"Wallis and Futuna","code"=>"WF"],
                ["id" => 240,"dial_code"=>967,"name"=>"Yemen","code"=>"YE"],
                ["id" => 241,"dial_code"=>260,"name"=>"Zambia","code"=>"ZM"],
                ["id" => 242,"dial_code"=>263,"name"=>"Zimbabwe","code"=>"ZW"]
        
        ]);
    }
}