<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParlourModuleSeeder extends Seeder
{
    public function run()
    {
        DB::table('parlour_module')->insert([
            ["id"=>1,"name"=>"Parlour Style"],
            ["id"=>2,"name"=>"Cow Standing"],
            ["id"=>3,"name"=>"Type of Cows"],
            ["id"=>4,"name"=>"Electricity"],
            ["id"=>5,"name"=>"Installation"],
            ["id"=>6,"name"=>"Delivery"],
            ["id"=>7,"name"=>"Rump Rails"],
            ["id"=>8,"name"=>"Front Guide Rails"],
            ["id"=>9,"name"=>"Back Guide rails"],
            ["id"=>10,"name"=>'Front Exit Gates'],
            ["id"=>11,"name"=>"Back Entrance Gates"],
            ["id"=>12,"name"=>"Gate control"],
            ["id"=>13,"name"=>"Pit Kerb Rail"],
            ["id"=>14,"name"=>"Stalling"],
            ["id"=>15,"name"=>"Stalling Extras"],
            ["id"=>16,"name"=>"Herringbone Vacuum Line"],
            ["id"=>17,"name"=>"Vacuum Outfit"],
            ["id"=>18,"name"=>"Pump Type"],
            ["id"=>19,"name"=>"Pulsation System"],
            ["id"=>20,"name"=>"Pulsation Type"],
            ["id"=>21,"name"=>"Cluster Units"],
            ["id"=>22,"name"=>"Herringbone Cluster Support"],
            ["id"=>23,"name"=>"Delivery Milk Pump"],
            ["id"=>24,"name"=>"Inline Filters"],
            ["id"=>25,"name"=>"Plate Cooler"],
            ["id"=>26,"name"=>"Bulk Tank Filling"],
            ["id"=>28,"name"=>"Bucket Assembly"],
            ["id"=>29,"name"=>"Bucket Qty"],
            ["id"=>30,"name"=>"Unit Control"],
            ["id"=>31,"name"=>"Milk Sensor"],
            ["id"=>32,"name"=>"Sampling Device"],
            ["id"=>33,"name"=>"Herringbone Easy Start"],
            ["id"=>34,"name"=>"Parlour Identification"],
            ["id"=>35,"name"=>"Transponder Type"],
            ["id"=>36,"name"=>"CIP"],
            ["id"=>37,"name"=>"System"],
            ["id"=>38,"name"=>"Chemical Pumps"],
            ["id"=>39,"name"=>"Herringbone Parlour wash drops"],
            ["id"=>40,"name"=>"Wash pump unit"],
            ["id"=>41,"name"=>"Animal Handling"],
            ["id"=>42,"name"=>"Crowd gate"],
            ["id"=>43,"name"=>"Animal Teat spray"],
            ["id"=>44,"name"=>"Udder washer"],
            ["id"=>45,"name"=>"Smart Collar Type"],
            ["id"=>46,"name"=>"Extender Unit"],
            ["id"=>47,"name"=>"Feed units"],
            ["id"=>48,"name"=>"In Parlour Feed control"],
            ["id"=>50,"name"=>"Touch Screen"],
            ["id"=>51,"name"=>"Voice Assist"],
            ["id"=>52,"name"=>"Herd Teat Spray"],
            ["id"=>53,"name"=>"Leg Dividers"],
            ["id"=>54,"name"=>"Rota Clean Wash Boom"]
            ["id"=>55,"name"=>"Rotary Style"],
            ["id"=>56,"name"=>"Rotary Deck"],
            ["id"=>57,"name"=>"Bail Type"],
            ["id"=>58,"name"=>"Retention Arms"],
            ["id"=>59,"name"=>"Rotary Pro Floor"],
            ["id"=>60,"name"=>"Rotation"],
            ["id"=>61,"name"=>"Pace Entrance System"],
            ["id"=>62,"name"=>"Outer Nib"],
            ["id"=>63,"name"=>"Inner Nib"],
            ["id"=>64,"name"=>"Pro Floor"],
            ["id"=>65,"name"=>"Rail Ramp"],
            ["id"=>66,"name"=>"Diversion Milk Pump"],
            ["id"=>67,"name"=>"Rotary Vacuum Line"],
            ["id"=>68,"name"=>"Rotary Easy Start"],
            ["id"=>69,"name"=>"Feed Types"],
            ["id"=>70,"name"=>"Feed Control"],
            ["id"=>71,"name"=>"Feeding Troughs"],
            ["id"=>72,"name"=>"Rotary Cluster Support"],
            ["id"=>73,"name"=>"Rotary Parlour Wash Drops"]
        ]);
    }
}